version: 2

updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
        patterns:
          - "*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
      eslint-config:
        patterns:
          - "eslint-config-*"
          - "eslint-plugin-*"
          - "typescript-eslint"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
